# Generated by Django 4.2.3 on 2023-09-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/')),
                ('subBranchId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mainBranchId', models.IntegerField()),
                ('SecondaryBranchId', models.IntegerField()),
                ('files', models.ManyToManyField(to='app.folderfiles')),
                ('subFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subfolder')),
            ],
        ),
        migrations.CreateModel(
            name='MainBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('files', models.ManyToManyField(to='app.folderfiles')),
                ('subFolder', models.ManyToManyField(to='app.subfolder')),
            ],
        ),
    ]
