# Generated by Django 4.2.3 on 2023-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_folderfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfolder',
            name='SecondaryBranchId',
            field=models.IntegerField(null=True),
        ),
    ]
