# Generated by Django 4.2.3 on 2023-09-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mainbranch_subfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfolder',
            name='subFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subfolder'),
        ),
    ]
