# Generated by Django 4.2.3 on 2023-09-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_subfolder_subfolder_subfolder_subfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfolder',
            name='subFolder',
        ),
        migrations.AddField(
            model_name='subfolder',
            name='subFolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subfolder'),
        ),
    ]
